name: Respond to Slash Command

on:
  repository_dispatch:
    types: [slash-command]

jobs:
  handle:
    runs-on: ubuntu-latest
    steps:
      - name: Log received payload
        run: |
          echo "👀 Received dispatch payload:"
          echo '${{ toJson(github.event) }}'

      - name: Call QR API
        id: qr
        run: |
          GAME="${{ github.event.client_payload.game }}"
          DISCORD_ID="${{ github.event.client_payload.user_id }}"
          INTERACTION_TOKEN="${{ github.event.client_payload.interaction_token }}"
          INTERACTION_ID="${{ github.event.client_payload.interaction_id }}"

          RESPONSE=$(curl -s "${{ secrets.SHEET_API_URL }}?discord_id=$DISCORD_ID&game=$GAME")
          echo "$RESPONSE" > response.json
          echo "🎯 Response: $RESPONSE"

      - name: Send Discord follow-up
        run: |
          CONTENT=$(jq -r '.qr // .error' response.json)
          echo "📤 Sending to Discord: $CONTENT"

          curl -X POST \
            "https://discord.com/api/v10/webhooks/${{ secrets.DISCORD_CLIENT_ID }}/$INTERACTION_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"content\": \"$CONTENT\"}"
